// web-tools/src/components/GrepIt.tsx
/*
 *   Copyright (c) 2024-2025. caoccao.com Sam Cao
 *   All rights reserved.

 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at

 *   http://www.apache.org/licenses/LICENSE-2.0

 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
import { useState, useEffect, useRef, useMemo } from 'react';
import Stack from '@mui/material/Stack';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import FormControlLabel from '@mui/material/FormControlLabel';
import Checkbox from '@mui/material/Checkbox';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import IconButton from '@mui/material/IconButton';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import HelpOutlineIcon from '@mui/icons-material/HelpOutline';

const fontFamily = '"Courier New", Courier, monospace';

const GrepIt = () => {
  const [caseSensitiveChecked, setCaseSensitiveChecked] = useState(false);
  const [modalChangeTemplateOpened, setModalChangeTemplateOpened] = useState(false);
  const [modalHelpOpened, setModalHelpOpened] = useState(false);
  const [multilineChecked, setMultilineChecked] = useState(false);
  const [removeDuplicatedChecked, setRemoveDuplicatedChecked] = useState(false);
  const [sortChecked, setSortChecked] = useState(false);

  const [changeTemplateValue, setChangeTemplateValue] = useState('_');
  const [inputValue, setInputValue] = useState('');
  const [patternValue, setPatternValue] = useState('[^\\r\\n]+');
  const [templateValue, setTemplateValue] = useState('');

  const [errorMessageCode, setErrorMessageCode] = useState('');
  const [errorMessageInput, setErrorMessageInput] = useState('');

  const textAreaTemplateRef = useRef<HTMLTextAreaElement>(null);
  const [selectionStart, setSelectionStart] = useState<number | null>(null);
  const [selectionEnd, setSelectionEnd] = useState<number | null>(null);

  // Set font family on mount and when modal opens
  useEffect(() => {
    const setFontFamily = () => {
      document.querySelectorAll<HTMLInputElement>('input').forEach((input) => {
        input.style.fontFamily = fontFamily;
      });
      document.querySelectorAll<HTMLTextAreaElement>('textarea').forEach((textarea) => {
        textarea.style.fontFamily = fontFamily;
      });
    };
    setFontFamily();
  }, [modalChangeTemplateOpened]);

  // Restore textarea selection
  useEffect(() => {
    if (selectionStart !== null && selectionEnd !== null && textAreaTemplateRef.current) {
      textAreaTemplateRef.current.selectionStart = selectionStart;
      textAreaTemplateRef.current.selectionEnd = selectionEnd;
      setSelectionStart(null);
      setSelectionEnd(null);
    }
  }, [selectionStart, selectionEnd]);

  const evaluateTemplate = (code: string, _: RegExpExecArray, i: number): string => {
    return eval(code);
  };

  const evaluateChangeTemplate = (code: string, _: string): string => {
    return eval(code);
  };

  // Compute output value
  const outputValue = useMemo(() => {
    setErrorMessageInput('');
    if (patternValue === '' || inputValue === '') {
      return '';
    }

    try {
      let flags = 'g';
      if (!caseSensitiveChecked) {
        flags += 'i';
      }
      if (multilineChecked) {
        flags += 'm';
      }
      const regex = new RegExp(patternValue, flags);
      let lines: Array<string> = [];
      let index = 0;
      for (const match of inputValue.matchAll(regex)) {
        const escapedTemplateValue =
          templateValue && templateValue !== '' ? templateValue : '${_[0]}';
        const line = evaluateTemplate('`' + escapedTemplateValue + '`', match, index);
        lines.push(line);
        ++index;
      }
      if (removeDuplicatedChecked) {
        const uniqueLines: Array<string> = [];
        const lineSet = new Set();
        lines.forEach((line) => {
          if (!lineSet.has(line)) {
            lineSet.add(line);
            uniqueLines.push(line);
          }
        });
        lines = uniqueLines;
      }
      if (sortChecked) {
        lines.sort();
      }
      return lines.length > 0 ? lines.map((line) => `${line}\n`).join('') : '';
    } catch (error) {
      if (error instanceof Error) {
        setErrorMessageInput(error.message);
      } else {
        setErrorMessageInput(`Unknown error ${error}.`);
      }
      return '';
    }
  }, [
    patternValue,
    inputValue,
    templateValue,
    caseSensitiveChecked,
    multilineChecked,
    removeDuplicatedChecked,
    sortChecked
  ]);

  const onClickChangeTemplate = () => {
    setModalChangeTemplateOpened(true);
  };

  const onClickCopy = () => {
    setErrorMessageInput('');
    navigator.clipboard.writeText(outputValue).catch((error) => {
      setErrorMessageInput(error.message);
    });
  };

  const onClickEscapeDollar = () => {
    setErrorMessageInput('');
    setTemplateValue(templateValue.replaceAll('$', '\\$'));
  };

  const onClickEscapeBackSlash = () => {
    setErrorMessageInput('');
    setTemplateValue(templateValue.replaceAll('\\', '\\\\'));
  };

  const onClickEscapeBackQuote = () => {
    setErrorMessageInput('');
    setTemplateValue(templateValue.replaceAll('`', '\\`'));
  };

  const onClickInputLabel = (event: React.MouseEvent) => {
    if (event.ctrlKey) {
      setInputValue('');
    }
  };

  const onClickModalChangeTemplateExecute = () => {
    setErrorMessageCode('');
    try {
      setTemplateValue(evaluateChangeTemplate(changeTemplateValue, templateValue));
      setModalChangeTemplateOpened(false);
    } catch (error) {
      if (error instanceof Error) {
        setErrorMessageCode(error.message);
      } else {
        setErrorMessageCode(`Unknown error ${error}.`);
      }
    }
  };

  const onClickModalHelp = () => {
    setModalHelpOpened(true);
  };

  const onClickPaste = () => {
    setErrorMessageInput('');
    navigator.clipboard
      .readText()
      .then((text) => {
        setInputValue(text);
      })
      .catch((error) => {
        setErrorMessageInput(error.message);
      });
  };

  const onClickPatternLabel = (event: React.MouseEvent) => {
    if (event.ctrlKey) {
      setPatternValue('');
    }
  };

  const onClickTemplateLabel = (event: React.MouseEvent) => {
    if (event.ctrlKey) {
      setTemplateValue('');
    }
  };

  const onCloseModalChangeTemplate = () => {
    setErrorMessageCode('');
    setModalChangeTemplateOpened(false);
  };

  const onCloseModalHelp = () => {
    setModalHelpOpened(false);
  };

  const onKeyupTemplate = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if ((event.ctrlKey || event.altKey) && textAreaTemplateRef.current) {
      const key = event.key;
      if (/^[0-9]$/.test(key)) {
        const start = textAreaTemplateRef.current.selectionStart;
        const end = textAreaTemplateRef.current.selectionEnd;
        const prefix = templateValue.slice(0, start);
        const suffix = templateValue.slice(end);
        setTemplateValue(`${prefix}\${_[${key}]}${suffix}`);
        const newPosition = start + 7;
        setSelectionStart(newPosition);
        setSelectionEnd(newPosition);
      }
    }
  };

  return (
    <>
      <Stack spacing={2} alignItems="stretch">
        <TextField
          label="Pattern *"
          value={patternValue}
          onChange={(e) => setPatternValue(e.target.value)}
          onClick={onClickPatternLabel}
          fullWidth
        />
        <TextField
          label="Template"
          multiline
          rows={5}
          value={templateValue}
          onChange={(e) => setTemplateValue(e.target.value)}
          onKeyUp={onKeyupTemplate}
          onClick={onClickTemplateLabel}
          inputRef={textAreaTemplateRef}
          fullWidth
        />
        <Box sx={{ display: 'flex', justifyContent: 'center', gap: 2, flexWrap: 'wrap' }}>
          <FormControlLabel
            control={
              <Checkbox
                checked={caseSensitiveChecked}
                onChange={(e) => setCaseSensitiveChecked(e.target.checked)}
              />
            }
            label="Case Sensitive"
          />
          <FormControlLabel
            control={
              <Checkbox
                checked={multilineChecked}
                onChange={(e) => setMultilineChecked(e.target.checked)}
              />
            }
            label="Multiline"
          />
          <FormControlLabel
            control={
              <Checkbox
                checked={removeDuplicatedChecked}
                onChange={(e) => setRemoveDuplicatedChecked(e.target.checked)}
              />
            }
            label="Remove Duplicated"
          />
          <FormControlLabel
            control={
              <Checkbox checked={sortChecked} onChange={(e) => setSortChecked(e.target.checked)} />
            }
            label="Sort"
          />
        </Box>
        <Box sx={{ display: 'flex', justifyContent: 'center', gap: 1, flexWrap: 'wrap' }}>
          <Button variant="contained" color="info" size="small" onClick={onClickEscapeBackSlash}>
            Escape \
          </Button>
          <Button variant="contained" color="info" size="small" onClick={onClickEscapeBackQuote}>
            Escape `
          </Button>
          <Button variant="contained" color="info" size="small" onClick={onClickEscapeDollar}>
            Escape $
          </Button>
          <Button variant="contained" color="info" size="small" onClick={onClickChangeTemplate}>
            Change Template
          </Button>
          <Button variant="contained" size="small" onClick={onClickPaste}>
            Paste
          </Button>
          <Button variant="contained" size="small" onClick={onClickCopy}>
            Copy
          </Button>
        </Box>
        <TextField
          label="Input *"
          multiline
          rows={10}
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onClick={onClickInputLabel}
          error={!!errorMessageInput}
          helperText={errorMessageInput}
          fullWidth
        />
        <TextField
          label="Output"
          multiline
          rows={10}
          value={outputValue}
          InputProps={{
            readOnly: true
          }}
          fullWidth
        />
        <Box sx={{ display: 'flex', justifyContent: 'center' }}>
          <IconButton color="warning" onClick={onClickModalHelp} size="large">
            <HelpOutlineIcon fontSize="large" />
          </IconButton>
        </Box>
      </Stack>

      <Dialog
        open={modalChangeTemplateOpened}
        onClose={onCloseModalChangeTemplate}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>Change Template by JavaScript Code</DialogTitle>
        <DialogContent>
          <Stack spacing={2} sx={{ mt: 1 }}>
            <TextField
              label="JavaScript Code *"
              multiline
              rows={10}
              value={changeTemplateValue}
              onChange={(e) => setChangeTemplateValue(e.target.value)}
              error={!!errorMessageCode}
              helperText={errorMessageCode}
              fullWidth
            />
            <Box sx={{ display: 'flex', justifyContent: 'center', gap: 2 }}>
              <Button variant="contained" color="error" onClick={onCloseModalChangeTemplate}>
                Cancel
              </Button>
              <Button variant="contained" onClick={onClickModalChangeTemplateExecute}>
                Execute
              </Button>
            </Box>
          </Stack>
        </DialogContent>
      </Dialog>

      <Dialog open={modalHelpOpened} onClose={onCloseModalHelp} maxWidth="lg" fullWidth>
        <DialogTitle>Help</DialogTitle>
        <DialogContent>
          <Stack spacing={2}>
            <Typography variant="h5">Template</Typography>
            <Typography variant="h6">Variables</Typography>
            <ul>
              <li>
                <Typography
                  component="code"
                  sx={{ backgroundColor: 'lightgray', px: 0.5, py: 0.2 }}
                >
                  _
                </Typography>{' '}
                - is the match result.
              </li>
              <li>
                <Typography
                  component="code"
                  sx={{ backgroundColor: 'lightgray', px: 0.5, py: 0.2 }}
                >
                  i
                </Typography>{' '}
                - is the index of the match result.
              </li>
            </ul>
            <Typography variant="h6">Keyboard Shortcuts</Typography>
            <ul>
              <li>
                <Typography
                  component="code"
                  sx={{ backgroundColor: 'lightgray', px: 0.5, py: 0.2 }}
                >
                  Ctrl/Alt+0
                </Typography>{' '}
                -{' '}
                <Typography
                  component="code"
                  sx={{ backgroundColor: 'lightgray', px: 0.5, py: 0.2 }}
                >
                  Ctrl/Alt+9
                </Typography>{' '}
                - inserts{' '}
                <Typography
                  component="code"
                  sx={{ backgroundColor: 'lightgray', px: 0.5, py: 0.2 }}
                >
                  {'${_[0]}'}
                </Typography>{' '}
                -{' '}
                <Typography
                  component="code"
                  sx={{ backgroundColor: 'lightgray', px: 0.5, py: 0.2 }}
                >
                  {'${_[9]}'}
                </Typography>{' '}
                to the template.
              </li>
            </ul>
          </Stack>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default GrepIt;

// web-tools/src/routes/grep-it.svelte
<script lang="ts">
  /*
    *   Copyright (c) 2024. caoccao.com Sam Cao
    *   All rights reserved.

    *   Licensed under the Apache License, Version 2.0 (the "License");
    *   you may not use this file except in compliance with the License.
    *   You may obtain a copy of the License at

    *   http://www.apache.org/licenses/LICENSE-2.0

    *   Unless required by applicable law or agreed to in writing, software
    *   distributed under the License is distributed on an "AS IS" BASIS,
    *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    *   See the License for the specific language governing permissions and
    *   limitations under the License.
    */
  import { afterUpdate, onMount } from 'svelte';
  import {
    ActionIcon,
    Button,
    Checkbox,
    Group,
    Modal,
    Stack,
    Textarea,
    TextInput,
    Title
  } from '@svelteuidev/core';
  import { QuestionMarkCircled } from 'radix-icons-svelte';

  const fontFamily = '"Courier New", Courier, monospace';

  let caseSensitiveChecked = false;
  let modalChangeTemplateOpened = false;
  let modalHelpOpened = false;
  let multilineChecked = false;
  let removeDuplicatedChecked = false;
  let sortChecked = false;

  let changeTemplateValue = '_';
  let inputValue = '';
  let outputValue = '';
  let patternValue = '[^\\r\\n]+';
  let templateValue = '';

  let errorMessageCode = '';
  let errorMessageInput = '';

  let textAreaTemplate: HTMLTextAreaElement;
  let textAreaTemplateSelectionStart: number | null = null;
  let textAreaTemplateSelectionEnd: number | null = null;

  afterUpdate(() => {
    if (textAreaTemplateSelectionStart !== null && textAreaTemplateSelectionEnd !== null) {
      textAreaTemplate.selectionStart = textAreaTemplateSelectionStart;
      textAreaTemplate.selectionEnd = textAreaTemplateSelectionEnd;
      textAreaTemplateSelectionStart = null;
      textAreaTemplateSelectionEnd = null;
    }
    if (modalChangeTemplateOpened) {
      setFontFamily();
    }
  });

  onMount(() => {
    setFontFamily();
    textAreaTemplate = document.getElementById('textAreaTemplate') as HTMLTextAreaElement;
  });

  function evaluateChangeTemplate(code: string, _: string): string {
    return eval(code);
  }

  function evaluateTemplate(code: string, _: RegExpExecArray, i: number): string {
    return eval(code);
  }

  $: {
    errorMessageInput = '';
    if (patternValue === '' || inputValue === '') {
      outputValue = '';
    } else {
      try {
        let flags = 'g';
        if (!caseSensitiveChecked) {
          flags += 'i';
        }
        if (multilineChecked) {
          flags += 'm';
        }
        const regex = new RegExp(patternValue, flags);
        let lines: Array<string> = [];
        let index = 0;
        for (const match of inputValue.matchAll(regex)) {
          const escapedTemplateValue =
            templateValue && templateValue !== '' ? templateValue : '${_[0]}';
          const line = evaluateTemplate('`' + escapedTemplateValue + '`', match, index);
          lines.push(line);
          ++index;
        }
        if (removeDuplicatedChecked) {
          const uniqueLines: Array<string> = [];
          const lineSet = new Set();
          lines.forEach((line) => {
            if (!lineSet.has(line)) {
              lineSet.add(line);
              uniqueLines.push(line);
            }
          });
          lines = uniqueLines;
        }
        if (sortChecked) {
          lines.sort();
        }
        outputValue = lines.length > 0 ? lines.map((line) => `${line}\n`).join('') : '';
      } catch (error) {
        outputValue = '';
        if (error instanceof Error) {
          errorMessageInput = error.message;
        } else {
          errorMessageInput = `Unknown error ${error}.`;
        }
      }
    }
  }

  function onClickChangeTemplate() {
    modalChangeTemplateOpened = true;
  }

  function onClickCopy() {
    errorMessageInput = '';
    navigator.clipboard.writeText(outputValue).catch((error) => {
      errorMessageInput = error.message;
    });
  }

  function onClickEscapeDollar() {
    errorMessageInput = '';
    templateValue = templateValue.replaceAll('$', '\\$');
  }

  function onClickEscapeBackSlash() {
    errorMessageInput = '';
    templateValue = templateValue.replaceAll('\\', '\\\\');
  }

  function onClickEscapeBackQuote() {
    errorMessageInput = '';
    templateValue = templateValue.replaceAll('`', '\\`');
  }

  function onClickInputLabel(event: CustomEvent<PointerEvent>) {
    if ((event as unknown as PointerEvent).ctrlKey) {
      inputValue = '';
    }
  }

  function onClickModalChangeTemplateExecute() {
    errorMessageCode = '';
    try {
      templateValue = evaluateChangeTemplate(changeTemplateValue, templateValue);
      modalChangeTemplateOpened = false;
    } catch (error) {
      if (error instanceof Error) {
        errorMessageCode = error.message;
      } else {
        errorMessageCode = `Unknown error ${error}.`;
      }
    }
  }

  function onClickModalHelp() {
    modalHelpOpened = true;
  }

  function onClickPaste() {
    errorMessageInput = '';
    navigator.clipboard
      .readText()
      .then((text) => {
        inputValue = text;
      })
      .catch((error) => {
        errorMessageInput = error.message;
      });
  }

  function onClickPatternLabel(event: CustomEvent<PointerEvent>) {
    if ((event as unknown as PointerEvent).ctrlKey) {
      patternValue = '';
    }
  }

  function onClickTemplateLabel(event: CustomEvent<PointerEvent>) {
    if ((event as unknown as PointerEvent).ctrlKey) {
      templateValue = '';
    }
  }

  function onCloseModalChangeTemplate() {
    errorMessageCode = '';
    modalChangeTemplateOpened = false;
  }

  function onCloseModalHelp() {
    modalHelpOpened = false;
  }

  function onKeyupTemplate(event: KeyboardEvent) {
    if (event.ctrlKey || event.altKey) {
      switch (event.key) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
          textAreaTemplateSelectionStart = textAreaTemplate.selectionStart;
          textAreaTemplateSelectionEnd = textAreaTemplate.selectionEnd;
          const prefix = templateValue.slice(0, textAreaTemplateSelectionStart);
          const suffix = templateValue.slice(textAreaTemplateSelectionEnd);
          templateValue = `${prefix}\${_[${event.key}]}${suffix}`;
          const newPosition = textAreaTemplateSelectionStart + 7;
          textAreaTemplateSelectionStart = newPosition;
          textAreaTemplateSelectionEnd = newPosition;
          break;
      }
    }
  }

  function setFontFamily() {
    for (const input of document.getElementsByTagName('input')) {
      input.style.fontFamily = fontFamily;
    }
    for (const input of document.getElementsByTagName('textarea')) {
      input.style.fontFamily = fontFamily;
    }
  }
</script>

<Stack align="stretch" justify="flex-start">
  <TextInput label="Pattern *" bind:value={patternValue} on:click={onClickPatternLabel} />
  <Textarea
    id="textAreaTemplate"
    label="Template"
    rows="5"
    required={false}
    bind:value={templateValue}
    on:keyup={onKeyupTemplate}
    on:click={onClickTemplateLabel}
  />
  <Group position="center" spacing="md">
    <Checkbox label="Case Sensitive" bind:checked={caseSensitiveChecked} />
    <Checkbox label="Multiline" bind:checked={multilineChecked} />
    <Checkbox label="Remove Duplicated" bind:checked={removeDuplicatedChecked} />
    <Checkbox label="Sort" bind:checked={sortChecked} />
  </Group>
  <Group position="center" spacing="md">
    <Button color="cyan" on:click={onClickEscapeBackSlash} size="sm">Escape \</Button>
    <Button color="cyan" on:click={onClickEscapeBackQuote} size="sm">Escape `</Button>
    <Button color="cyan" on:click={onClickEscapeDollar} size="sm">Escape $</Button>
    <Button color="cyan" on:click={onClickChangeTemplate} size="sm">Change Template</Button>
    <Button on:click={onClickPaste} size="sm">Paste</Button>
    <Button on:click={onClickCopy} size="sm">Copy</Button>
  </Group>
  <Textarea
    label="Input *"
    rows="10"
    error={errorMessageInput}
    bind:value={inputValue}
    on:click={onClickInputLabel}
  />
  <Textarea
    label="Output"
    rows="10"
    readonly={true}
    required={false}
    variant="filled"
    value={outputValue}
  />
  <Group position="center" spacing="md">
    <ActionIcon color="yellow" variant="outline" size={36} on:click={onClickModalHelp}>
      <QuestionMarkCircled size={24} />
    </ActionIcon>
  </Group>
</Stack>
<Modal
  title="Change Template by JavaScript Code"
  centered={true}
  size="lg"
  opened={modalChangeTemplateOpened}
  on:close={onCloseModalChangeTemplate}
>
  <Stack align="stretch" justify="flex-start">
    <Textarea
      label="JavaScript Code *"
      rows="10"
      bind:value={changeTemplateValue}
      error={errorMessageCode}
    />
    <Group position="center" spacing="md">
      <Button color="red" on:click={onCloseModalChangeTemplate}>Cancel</Button>
      <Button on:click={onClickModalChangeTemplateExecute}>Execute</Button>
    </Group>
  </Stack>
</Modal>
<Modal title="Help" centered={true} size="xl" opened={modalHelpOpened} on:close={onCloseModalHelp}>
  <Stack align="stretch" justify="flex-start">
    <Title order={3}>Template</Title>
    <Title order={4}>Variables</Title>
    <ul>
      <li>
        <code>_</code> - is the match result.
      </li>
      <li>
        <code>i</code> - is the index of the match result.
      </li>
    </ul>
    <Title order={4}>Keyboard Shortcuts</Title>
    <ul>
      <li>
        <code>Ctrl/Alt+0</code> - <code>Ctrl/Alt+9</code> - inserts
        <code>&#36;&#123;_[0]}</code> - <code>&#36;&#123;_[9]}</code> to the template.
      </li>
    </ul>
  </Stack>
</Modal>

<style>
  code {
    background-color: lightgray;
    padding: 0.1em 0.2em;
  }
</style>
